# Generated by Django 6.1.1 on 2026-09-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origUrl', models.CharField(max_length=20)),
                ('shortUrl', models.CharField(max_length=10)),
            ],
        ),
    ]
