# Generated by Django 6.1.1 on 2026-09-16 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='shortUrl',
            new_name='shortcode',
        ),
    ]
